---
- block:
  - name: Configure docker user
    ansible.builtin.import_tasks: users.yml
  - name: Mount docker disk if needed
    ansible.builtin.import_tasks: mount-extra-volume.yml
  - name: Harden docker
    ansible.builtin.import_tasks: harden-docker.yml
    tags:
    - molecule-notest
  become: true