---
# handlers file for bootstrap-docker/
- name: reboot
  become: yes
  ansible.builtin.reboot:

- name: auditd restart
  become: yes
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: load audit rules
  become: yes
  ansible.builtin.command: "/sbin/augenrules --load"

- name: docker restart
  become: yes
  ansible.builtin.service:
    name: docker
    state: restarted

- name: netfilter persistent restart
  become: yes
  ansible.builtin.service:
    name: netfilter-persistent
    state: restarted

- name: reload ufw
  become: yes
  community.general.ufw:
    state: reloaded
