---
roles:
- src: https://github.com/robertdebock/ansible-role-bootstrap
  name: robertdebock.bootstrap
  version: 5.2.6
- src: https://github.com/robertdebock/ansible-role-epel
  name: robertdebock.epel
  version: 3.1.2
- src: https://github.com/robertdebock/ansible-role-buildtools
  name: robertdebock.buildtools
  version: 3.1.2
- src: https://github.com/robertdebock/ansible-role-python_pip
  name: robertdebock.python_pip
  version: 4.2.2
- src: https://github.com/robertdebock/ansible-role-core_dependencies
  name: robertdebock.core_dependencies
  version: 2.1.1
- src: https://github.com/robertdebock/ansible-role-docker_ce
  name: robertdebock.docker_ce
  version: 3.2.1
- src: https://github.com/robertdebock/ansible-role-docker_compose
  name: robertdebock.docker_compose
  version: 2.1.0
collections:
  - name: ansible.posix
