---
roles:
- src: https://github.com/geerlingguy/ansible-role-docker
  name: geerlingguy.docker
  version: 2.7.0
- src: https://github.com/geerlingguy/ansible-role-pip
  name: geerlingguy.pip
  version: 2.0.0
collections:
  - name: ansible.posix
